package com.cantonadong.pinote;
import android.app.*;import android.content.*;import android.os.IBinder;
public class ReminderService extends Service{
 static final String CHANNEL="pinned_reminder",CLEAR="clear_pinned_reminder",UNPIN="unpin_reminder",DELETE="delete_reminder",DATA_CLEARED="com.cantonadong.pinote.DATA_CLEARED";static final int ID=1401;
 static void sync(Context c){ReminderStore.load(c);Intent i=new Intent(c,ReminderService.class);if(ReminderStore.pinned()!=null)c.startForegroundService(i);else{i.setAction(CLEAR);c.startService(i);}}
 boolean zh(){return"zh".equals(getResources().getConfiguration().getLocales().get(0).getLanguage());}String l(String cn,String en){return zh()?cn:en;}
 @Override public void onCreate(){super.onCreate();NotificationChannel ch=new NotificationChannel(CHANNEL,l("Pinote 固定提醒","Pinned Pinote"),NotificationManager.IMPORTANCE_LOW);ch.setSound(null,null);ch.setDescription(l("显示当前保存的 Pinote 内容","Shows your current pinned Pinote"));getSystemService(NotificationManager.class).createNotificationChannel(ch);}
 @Override public int onStartCommand(Intent i,int f,int n){String action=i==null?null:i.getAction();if(CLEAR.equals(action)){removeAndStop();return START_NOT_STICKY;}if(UNPIN.equals(action)){ReminderStore.load(this);ReminderStore.Reminder r=ReminderStore.pinned();if(r!=null){r.pinned=false;ReminderStore.save(this);}removeAndStop();return START_NOT_STICKY;}if(DELETE.equals(action)){ReminderStore.items.clear();ReminderStore.save(this);sendBroadcast(new Intent(DATA_CLEARED).setPackage(getPackageName()));removeAndStop();return START_NOT_STICKY;}ReminderStore.load(this);ReminderStore.Reminder r=ReminderStore.pinned();if(r==null){removeAndStop();return START_NOT_STICKY;}startForeground(ID,build(r));return START_STICKY;}
 void removeAndStop(){stopForeground(STOP_FOREGROUND_REMOVE);getSystemService(NotificationManager.class).cancel(ID);stopSelf();}
 Notification build(ReminderStore.Reminder r){PendingIntent pi=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);PendingIntent unpin=PendingIntent.getService(this,1,new Intent(this,ReminderService.class).setAction(UNPIN),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);PendingIntent delete=PendingIntent.getService(this,2,new Intent(this,ReminderService.class).setAction(DELETE),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);StringBuilder b=new StringBuilder();if("todo".equals(r.type))for(ReminderStore.Todo t:r.todos){if(t.done)continue;if(b.length()>0)b.append('\n');b.append("☐  ").append(t.text);}else b.append(r.text);String body=threeLines(b.toString());return new Notification.Builder(this,CHANNEL).setSmallIcon(R.drawable.ic_notification).setContentText(body.replace('\n',' ')).setStyle(new Notification.BigTextStyle().bigText(body)).setContentIntent(pi).addAction(new Notification.Action.Builder(R.drawable.ic_pin,l("取消固定","Unpin"),unpin).build()).addAction(new Notification.Action.Builder(R.drawable.ic_delete,l("删除","Delete"),delete).build()).setOngoing(true).setOnlyAlertOnce(true).setCategory(Notification.CATEGORY_REMINDER).build();}
 String oneLine(String value,int max){String s=value.replace('\n',' ').replace('\r',' ').trim();return s.length()>max?s.substring(0,max-1)+"…":s;}
 String threeLines(String value){String normalized=value.replace("\r","");String[] raw=normalized.split("\n");StringBuilder out=new StringBuilder();int lines=0;for(String line:raw){String s=line.trim();while(!s.isEmpty()&&lines<3){int end=Math.min(29,s.length());if(out.length()>0)out.append('\n');out.append(s,0,end);s=s.substring(end).trim();lines++;}if(lines>=3)break;}return out.toString();}
 @Override public IBinder onBind(Intent i){return null;}
}
