package com.cantonadong.pinote;
import android.content.Context;import android.graphics.Color;import android.view.*;import android.widget.*;
final class SwipeDeleteLayout extends FrameLayout{
 interface Listener{void deleted();}interface ReorderListener{void started();void moved(float deltaY);void ended();}final View card,red,divider,leftTrash,rightTrash;final Listener listener;final android.os.Handler handler=new android.os.Handler(android.os.Looper.getMainLooper());ReorderListener reorderListener;Runnable longPress;float down,downY,downRawY,last;boolean drag,swipeEnabled=true,reorderEnabled,reordering;final float threshold,slop,holdSlop,deleteSize;
 SwipeDeleteLayout(Context c,View content,Listener l){super(c);setClipChildren(true);setClipToPadding(true);listener=l;float density=c.getResources().getDisplayMetrics().density;threshold=120*density;slop=8*density;holdSlop=24*density;deleteSize=48*density;FrameLayout layer=new FrameLayout(c);layer.setBackgroundColor(Color.WHITE);divider=new View(c);divider.setBackgroundColor(Color.rgb(229,231,235));FrameLayout.LayoutParams lineParams=new FrameLayout.LayoutParams(-1,Math.max(1,(int)density),Gravity.BOTTOM);lineParams.leftMargin=(int)(38*density);layer.addView(divider,lineParams);ImageView left=trash(c,density),right=trash(c,density);leftTrash=left;rightTrash=right;leftTrash.setTranslationX(-deleteSize);rightTrash.setTranslationX(deleteSize);FrameLayout.LayoutParams leftParams=new FrameLayout.LayoutParams((int)deleteSize,(int)deleteSize,Gravity.LEFT|Gravity.CENTER_VERTICAL);FrameLayout.LayoutParams rightParams=new FrameLayout.LayoutParams((int)deleteSize,(int)deleteSize,Gravity.RIGHT|Gravity.CENTER_VERTICAL);layer.addView(left,leftParams);layer.addView(right,rightParams);red=layer;red.setVisibility(VISIBLE);addView(red,new LayoutParams(-1,-1));card=content;card.setBackgroundColor(Color.TRANSPARENT);addView(card,new LayoutParams(-1,-2));}
 void showDeleteFor(float offset){red.setVisibility(VISIBLE);if(offset>0){leftTrash.setVisibility(VISIBLE);rightTrash.setVisibility(INVISIBLE);leftTrash.setTranslationX(-deleteSize+Math.min(offset,deleteSize));}else{leftTrash.setVisibility(INVISIBLE);rightTrash.setVisibility(VISIBLE);rightTrash.setTranslationX(deleteSize-Math.min(-offset,deleteSize));}}
 void setSwipeEnabled(boolean enabled){swipeEnabled=enabled;if(!enabled){if(getParent()!=null)getParent().requestDisallowInterceptTouchEvent(false);reset();}}
 void setReorderEnabled(boolean enabled){reorderEnabled=enabled;if(!enabled)cancelPendingLongPress();}void setReorderListener(ReorderListener l){reorderListener=l;}void cancelPendingLongPress(){if(longPress!=null)handler.removeCallbacks(longPress);longPress=null;}
 void scheduleLongPress(){cancelPendingLongPress();if(!reorderEnabled||reorderListener==null)return;if(getParent()!=null)getParent().requestDisallowInterceptTouchEvent(true);longPress=()->{reordering=true;card.cancelLongPress();getParent().requestDisallowInterceptTouchEvent(true);reorderListener.started();};handler.postDelayed(longPress,500);}
 void finishReorder(){cancelPendingLongPress();if(reordering){reordering=false;if(getParent()!=null)getParent().requestDisallowInterceptTouchEvent(false);reorderListener.ended();}}
 @Override public boolean onInterceptTouchEvent(android.view.MotionEvent e){switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:down=e.getX();downY=e.getY();downRawY=e.getRawY();last=0;drag=false;card.animate().cancel();card.setTranslationX(0);card.setAlpha(1);leftTrash.setVisibility(INVISIBLE);rightTrash.setVisibility(INVISIBLE);leftTrash.setTranslationX(-deleteSize);rightTrash.setTranslationX(deleteSize);scheduleLongPress();return false;case MotionEvent.ACTION_MOVE:if(reordering){reorderListener.moved(e.getRawY()-downRawY);return true;}float dx=e.getX()-down,dy=e.getY()-downY;if(Math.abs(dy)>holdSlop&&Math.abs(dy)>Math.abs(dx)){cancelPendingLongPress();getParent().requestDisallowInterceptTouchEvent(false);return false;}last=dx;if(swipeEnabled&&Math.abs(last)>slop&&Math.abs(dx)>Math.abs(dy)){cancelPendingLongPress();drag=true;showDeleteFor(last);getParent().requestDisallowInterceptTouchEvent(true);return true;}return false;case MotionEvent.ACTION_CANCEL:case MotionEvent.ACTION_UP:if(reordering){finishReorder();return true;}cancelPendingLongPress();if(getParent()!=null)getParent().requestDisallowInterceptTouchEvent(false);return false;}return false;}
 @Override public boolean onTouchEvent(android.view.MotionEvent e){if(reordering){if(e.getActionMasked()==MotionEvent.ACTION_MOVE)reorderListener.moved(e.getRawY()-downRawY);else if(e.getActionMasked()==MotionEvent.ACTION_UP||e.getActionMasked()==MotionEvent.ACTION_CANCEL)finishReorder();return true;}if(!swipeEnabled)return false;switch(e.getActionMasked()){case MotionEvent.ACTION_MOVE:last=e.getX()-down;showDeleteFor(last);card.setTranslationX(last);return true;case MotionEvent.ACTION_UP:getParent().requestDisallowInterceptTouchEvent(false);if(Math.abs(last)>=threshold){showDeleteFor(last);card.animate().translationX(last>0?getWidth():-getWidth()).alpha(0).setDuration(180).withEndAction(listener::deleted).start();}else reset();return true;case MotionEvent.ACTION_CANCEL:getParent().requestDisallowInterceptTouchEvent(false);reset();return true;}return true;}
 void reset(){leftTrash.animate().translationX(-deleteSize).setDuration(160).start();rightTrash.animate().translationX(deleteSize).setDuration(160).start();card.animate().translationX(0).setDuration(160).withEndAction(()->{leftTrash.setVisibility(INVISIBLE);rightTrash.setVisibility(INVISIBLE);}).start();}
 ImageView trash(Context c,float density){ImageView v=new ImageView(c);v.setImageResource(R.drawable.delete_icon);v.setScaleType(ImageView.ScaleType.FIT_XY);return v;}
}
