const samples={normal:{title:'明日工作计划',blocks:[{type:'text',text:'准备周会汇报材料'},{type:'todo',text:'完成用户调研报告',done:true},{type:'todo',text:'设计新功能原型',done:false}]},edge:{title:'这是一个用于验证单行截断效果的非常非常长的提醒标题',blocks:[{type:'text',text:'这是一段很长的普通文本，用于验证多行自动换行。\n第二行应保留原始换行。'},{type:'todo',text:'一条特别长的 Todo，确保文字自然换行时 Checkbox 保持顶部对齐',done:false},{type:'todo',text:'已经完成但依然保留显示的事项',done:true}]}};
let model=structuredClone(samples.normal),deleted=null,timer=null;
const app=document.querySelector('#app'),snack=document.querySelector('#snackbar');
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logo=()=>'<span class="brand-icon"><svg viewBox="0 0 32 32" aria-hidden="true"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#6d9cff"/><stop offset="1" stop-color="#3978f2"/></linearGradient></defs><rect x="5" y="5" width="22" height="24" rx="4" fill="url(#g)"/><path d="M10 3v5M22 3v5M10 13h12M10 18h12M10 23h8" stroke="white" stroke-width="2" stroke-linecap="round"/><circle cx="25.5" cy="25.5" r="4.2" fill="white"/><path d="M23.5 26.5h4M24.2 26.5v-1.8a1.3 1.3 0 012.6 0v1.8" stroke="#3978f2" stroke-width="1.25" stroke-linecap="round"/></svg></span>';
const shell=inner=>`<header class="header">${logo()}<div><h1>提醒记</h1><p>重要的事，时刻看得见</p></div></header>${inner}`;
function render(){const state=document.querySelector('#state').value;if(document.querySelector('#scene').value==='notification')return renderNotification(state);if(state==='loading'){app.innerHTML=shell('<div class="skeleton"><div class="sk"></div><div class="sk"></div><div class="sk"></div><div class="sk"></div></div>');return}if(state==='empty'){app.innerHTML=shell('<div class="field-label">标题</div><div class="title-field" style="color:var(--secondary);font-weight:400">添加标题</div><div class="empty"><div class="plus">＋</div><b>写下第一条内容</b><span>文本或 Todo 都可以</span></div>');return}if(state==='error'){app.innerHTML=shell('<div class="field-label">标题</div><div class="title-field">明日工作计划</div><div class="error">无法同步系统通知。提醒内容已安全保存在本机。<button>重试</button></div>');return}const trash='<svg viewBox="0 0 24 24" fill="none"><path d="M4 7h16M9 3h6l1 4H8l1-4zM7 7l1 14h8l1-14M10 11v6M14 11v6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>';const blocks=model.blocks.map((b,i)=>`<div class="swipe-wrap" data-i="${i}"><div class="delete-bg"><span>${trash}</span><span>${trash}</span></div><div class="block ${b.type==='todo'?'todo':''} ${b.done?'done':''}">${b.type==='todo'?`<span class="check">${b.done?'✓':''}</span>`:''}<span class="content">${esc(b.text).replaceAll('\n','<br>')}</span></div></div>`).join('');app.innerHTML=shell(`<div class="field-label">标题</div><div class="title-field">${esc(model.title)}</div><div class="section-title"><b>内容</b><button class="add">＋ 添加</button></div><div class="list">${blocks}</div>`);bindGestures()}
function renderNotification(state){if(state==='empty'){app.innerHTML='<div class="notification-stage"><div class="empty"><b>没有常驻通知</b><span>提醒内容为空时自动移除</span></div></div>';return}if(state==='loading'){app.innerHTML='<div class="notification-stage"><div class="skeleton"><div class="sk"></div><div class="sk"></div><div class="sk"></div></div></div>';return}if(state==='error'){app.innerHTML='<div class="notification-stage"><div class="error">通知权限未开启，当前无法显示常驻提醒。<button>返回应用重试</button></div></div>';return}const lines=model.blocks.map(b=>b.type==='todo'?`${b.done?'☑':'☐'} ${esc(b.text)}`:esc(b.text).replaceAll('\n','<br>')).join('<br>');app.innerHTML=`<div class="notification-stage"><div class="notification">${logo()}<div><h2>${esc(model.title)}</h2><div class="notification-lines">${lines}</div></div><span class="now">现在</span></div><div class="notification-hint">系统通知展开样式 · 内容修改后实时同步</div></div>`}
function bindGestures(){document.querySelectorAll('.swipe-wrap').forEach(w=>{const card=w.querySelector('.block');let start=0,dx=0,drag=false;w.onpointerdown=e=>{start=e.clientX;dx=0;drag=true;card.setPointerCapture(e.pointerId)};w.onpointermove=e=>{if(!drag)return;dx=e.clientX-start;card.style.transition='none';card.style.transform=`translateX(${dx}px)`};w.onpointerup=()=>{drag=false;card.style.transition='';if(Math.abs(dx)>105)remove(+w.dataset.i,dx);else card.style.transform=''};if(card.classList.contains('todo'))card.onclick=()=>{if(Math.abs(dx)>8)return;model.blocks[+w.dataset.i].done=!model.blocks[+w.dataset.i].done;render()}})}
function remove(i,dir=1){const item=model.blocks[i];if(!item)return;deleted={item,index:i};const card=document.querySelector(`[data-i="${i}"] .block`);if(card){card.style.transform=`translateX(${dir>0?430:-430}px)`;card.style.opacity='0'}setTimeout(()=>{model.blocks.splice(i,1);render();showSnack(`已删除「${item.text.slice(0,12)}${item.text.length>12?'…':''}」`)},180)}
function showSnack(text){clearTimeout(timer);document.querySelector('#snackText').innerHTML=`${esc(text)}<small>2 秒内可撤销</small>`;snack.classList.add('show');timer=setTimeout(()=>{snack.classList.remove('show');deleted=null},2000)}
document.querySelector('#undo').onclick=()=>{if(deleted){model.blocks.splice(deleted.index,0,deleted.item);deleted=null;clearTimeout(timer);snack.classList.remove('show');render()}};
document.querySelector('#state').onchange=e=>{if(samples[e.target.value])model=structuredClone(samples[e.target.value]);render()};
document.querySelector('#scene').onchange=render;
document.querySelector('#replay').onclick=()=>{document.querySelector('#scene').value='editor';document.querySelector('#state').value='normal';model=structuredClone(samples.normal);render();setTimeout(()=>remove(1,-1),350)};
render();
